### ISSUE TITLE
Reopen Orchestra shows Port 5224 is already in use (EADDRINUSE)

### ISSUE THREAD

**Issue by swissmanu** [swissmanu/orchestra#2]
closing and reopen Orchestra does not work. application crashes and states `EADRINUSE 0.0.0.0:5224`. this can be backtracked to the UDP socket `harmonyhubjs-discover` uses for discovering new hubs.

* issue in `harmonyhubjs-discover`: https://github.com/swissmanu/harmonyhubjs-discover/issues/5
* might be related to https://github.com/swissmanu/harmonyhubjs-discover/issues/4

**Comment by hipstersmoothie** [comment]
I'm seeing this too. Cant free that port in anyway atm either :(

**Comment by swissmanu** [comment]
should be fixed with the latest release `1.1.0` since i was not able to reproduce anymore.
can you confirm this, @hipstersmoothie? thx :)

https://github.com/swissmanu/orchestra/releases/tag/v1.1.0

**Comment by BjornBengtsson** [comment]
Hi 

No, sorry - still get an error message (see attached)

Best 
Bjorn

Phone: (+45)22655242
Mail: cph.bjorn@gmail.com <mailto:cph.bjorn@gmail.com>
On 25. Nov 2016 Week 47, at 21:39, Manuel Alabor <notifications@github.com> wrote:

should be fixed with the latest release 1.1.0 since i was not able to reproduce anymore.
can you confirm this, @hipstersmoothie <https://github.com/hipstersmoothie>? thx :)

https://github.com/swissmanu/orchestra/releases/tag/v1.1.0 <https://github.com/swissmanu/orchestra/releases/tag/v1.1.0>

**Comment by swissmanu** [comment]
can you guys give me more information about your system? (click the apple icon in the menu bar and click "About this Mac...".
what version of macOS do you use?

**Comment by BjornBengtsson** [comment]
Bjørn Bengtsson
Egegade 6, 2. sal
2200 København N

Mobil: 22655242
Mail: cph.bjorn@gmail.com <mailto:cph.bjorn@gmail.com>
On 26. Nov 2016 Week 47, at 12:41, Manuel Alabor <notifications@github.com> wrote:

can you guys give me more information about your system? (click the apple icon in the menu bar and click "About this Mac...".
what version of macOS do you use?

**Comment by swissmanu** [comment]
there went probably something wrong with your reply, @BjornBengtsson. only signatures were transmitted ;)

**Comment by BjornBengtsson** [comment]
A screenshot of my "About This Mac" info should have been attached. Is it attached to this mail?

However, I am running mac OS 10.12.1.

Bjorn Bengtsson
Egegade 6, 2. sal
Copenhagen 2200 N
DENMARK

Phone: (+45)22655242
Mail: cph.bjorn@gmail.com <mailto:cph.bjorn@gmail.com>
On 28. Nov 2016 Week 48, at 08:25, Manuel Alabor <notifications@github.com> wrote:

there went probably something wrong with your reply, @BjornBengtsson <https://github.com/BjornBengtsson>. only signatures were transmitted ;)
